root: true
extends: airbnb-base
plugins:
  - import
env:
  es6: true
  node: true
rules:
  no-param-reassign: 0
  no-plusplus: 0
  no-restricted-syntax: 0
  comma-dangle: 0
  class-methods-use-this: 0
  no-nested-ternary: 0
  no-confusing-arrow:
    - error
    - allowParens: true
